name: Build and Release

on:
  push:
    branches:
      - feat/*
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'beta[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+-[a-zA-Z0-9]+[0-9]+.[0-9]+'
      - '[0-9]+-[a-zA-Z0-9]+[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-[a-zA-Z0-9]+[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+[0-9]+.[0-9]+'

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'https://www.zaproxy.org/'
      
    
